## Generate clock signal and attach to clk
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]


## Reset as right most switch
set_property PACKAGE_PIN V17 [get_ports {reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]

## LED pins from right to left attached to led
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]


## Segments of the seven segment display attached to LED_out
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]


## Each of the 4 segments of the display attached to anode_select
set_property PACKAGE_PIN U2 [get_ports {anode_select[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode_select[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode_select[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode_select[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anode_select[3]}]

    set_property PACKAGE_PIN U18 [get_ports button_input[4]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button_input[4]]
set_property PACKAGE_PIN T18 [get_ports button_input[0]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button_input[0]]
set_property PACKAGE_PIN W19 [get_ports button_input[1]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button_input[1]]
set_property PACKAGE_PIN T17 [get_ports button_input[3]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button_input[3]]
set_property PACKAGE_PIN U17 [get_ports button_input[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button_input[2]]
